os:
  - linux
language: go
go:
  - 1.13.x

env: 
  global:
    - GOTFLAGS="-race"
  matrix:
    - BUILD_DEPTYPE=gomod

  
# disable travis install
install: 
  - true

script:

notifications:
  email: false